# Pythonのベースイメージを使用
FROM python:3.9

# 必要なライブラリのインストール（バージョン指定なし）
RUN pip install numpy==1.26.3 \
                pandas==2.2.0 \
                scikit-learn==1.4.0 \
                matplotlib==3.8.2 \
                seaborn==0.13.1 \
                xgboost==2.0.3 \
                lightgbm==4.2.0 \
                catboost==1.2.2 \
                torch==2.1.2 \
                lightning==2.1.3 \
                japanize-matplotlib==1.1.3 \
                ipywidgets==7.6.5 \
                miceforest==5.7.0 \
                shap==0.40.0 \
                tabpfn==0.1.9 \
                notebook \
                jupyterlab \
                -f https://download.pytorch.org/whl/torch_stable.html